spring.application.name=demo

#config database
###
spring.datasource.url=jdbc:mysql://localhost:3306/qlinsu
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
###

# config jwt
leo.jwt.base64-secret=vvQpfPDCAkUuDFOXI1fnbsv6wgNShquGKeT5dwUXpA3AKh2nzm12bcR4o3kOS3kSZ56WnnnEA0msLIOQ1Yjbrw==

#expiration: 100 day (seconds)
leo.jwt.token-validity-in-seconds=8640000
#
###
###


